### Initial Setup


In [ ]:
# Importing necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [ ]:
# Reading the dataset
df = pd.read_csv('online_advertising_performance_data.csv')

### Data Preprocessing


In [ ]:
# print(df.info())
# print(df.describe())
# print(df.shape)
# print(df.columns)

(15408, 12)
Index(['month', 'day', 'campaign_number', 'user_engagement', 'banner',
       'placement', 'displays', 'cost', 'clicks', 'revenue',
       'post_click_conversions', 'post_click_sales_amount'],
      dtype='object')


In [ ]:
# Changing the campaign_number column to just the number
df['campaign_number'] = df['campaign_number'].str.replace('camp', '')
df['campaign_number'] = df['campaign_number'].astype(int)
print(df['campaign_number'].unique())

[1 2 3]


In [8]:

# Changing User Engagement to numbers
engagement_mapping = {
    'High': 3,
    'Medium': 2,
    'Low': 1
}
df['user_engagement'] = df['user_engagement'].map(engagement_mapping)
print(df['user_engagement'].unique())

[3 1 2]


In [9]:
# Using Label Encoding for banner column
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['banner'] = label_encoder.fit_transform(df['banner'])
print(df['banner'].unique())

[0 1 2 3 4 5 6 7]


In [10]:
# Using Label Encoding for placement column
df['placement'] = label_encoder.fit_transform(df['placement'])
print(df['placement'].unique())

[0 1 2 4 3 5]


In [11]:
# Using Label Encoding for Month column
df['month'] = label_encoder.fit_transform(df['month']) 
print(df['month'].unique())

[0 2 1]


In [15]:
# Removing the last 2 unnamed columns from the dataset
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [ ]:
# Handling missing values
df.isnull().sum()
# As there are no missing values, we can proceed with the analysis

month                      0
day                        0
campaign_number            0
user_engagement            0
banner                     0
placement                  0
displays                   0
cost                       0
clicks                     0
revenue                    0
post_click_conversions     0
post_click_sales_amount    0
dtype: int64

### Analyzing the Data


 What is the overall trend in user engagement throughout the campaign period?

In [ ]:
print("Unique months:", df['month'].unique())
print("Unique days:", df['day'].unique())


Unique months: [0 2 1]
Unique days: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31]
